services:
  client:
    build: 
      context: ./client
      target: dev
    ports:
      - "8080:8080"
    depends_on: 
      - server
    volumes:
      - /usr/src/app/client/node_modules
      - ./client:/usr/src/app/client

  server:
    build: 
      context: ./server
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: local
    volumes:
      - ./server/local.env:/usr/src/app/local.env
      - ./server:/usr/src/app/server