#!/bin/sh
export HUSKY_GIT_DIR='../.git'
. "$(dirname "$0")/_/husky.sh"

#Run linter
npm run lint

# Exit if the lint fails
if [ $? -ne 0 ]; then
  echo "Lint failed, commit denied"
  exit 1
fi
npm lint
